import { ApolloProvider } from '@/components/providers/apollo-provider';
import { ToastProvider } from '@/components/ui/toast';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Plus_Jakarta_Sans } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const plusJakarta = Plus_Jakarta_Sans({
  variable: '--font-plus-jakarta',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${plusJakarta.variable} antialiased`}
      >
        <ApolloProvider>
          <NextTopLoader
            color="#ffffff"
            initialPosition={0.08}
            crawlSpeed={100}
            height={1}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={100}
            shadow="0 0 10px #ffffff,0 0 5px #ffffff"
          />
          <ToastProvider>{children}</ToastProvider>
        </ApolloProvider>
      </body>
    </html>
  );
}
